imagenet_templates_small = [
    "a photo of a {}",
    "a rendering of a {}",
    "a cropped photo of the {}",
    "the photo of a {}",
    "a photo of a clean {}",
    "a photo of a dirty {}",
    "a dark photo of the {}",
    "a photo of my {}",
    "a photo of the cool {}",
    "a close-up photo of a {}",
    "a bright photo of the {}",
    "a cropped photo of a {}",
    "a photo of the {}",
    "a good photo of the {}",
    "a photo of one {}",
    "a close-up photo of the {}",
    "a rendition of the {}",
    "a photo of the clean {}",
    "a rendition of a {}",
    "a photo of a nice {}",
    "a good photo of a {}",
    "a photo of the nice {}",
    "a photo of the small {}",
    "a photo of the weird {}",
    "a photo of the large {}",
    "a photo of a cool {}",
    "a photo of a small {}",
]

imagenet_style_templates_small = [
    "a painting in the style of {}",
    "a rendering in the style of {}",
    "a cropped painting in the style of {}",
    "the painting in the style of {}",
    "a clean painting in the style of {}",
    "a dirty painting in the style of {}",
    "a dark painting in the style of {}",
    "a picture in the style of {}",
    "a cool painting in the style of {}",
    "a close-up painting in the style of {}",
    "a bright painting in the style of {}",
    "a cropped painting in the style of {}",
    "a good painting in the style of {}",
    "a close-up painting in the style of {}",
    "a rendition in the style of {}",
    "a nice painting in the style of {}",
    "a small painting in the style of {}",
]

person_templates = [
    "a photo of a happy {}",
    "a rendering of a smiling {}",
    "a cropped photo of the cheerful {}",
    "the photo of a content {}",
    "a photo of a confident {}",
    "a photo of a successful {}",
    "a candid shot of the friendly {}",
    "a photo of my joyful {}",
    "a photo of the cool {}",
    "a close-up photo of a stylish {}",
    "a bright photo of the young {}",
    "a cropped photo of a fashionable {}",
    "a photo of the caring {}",
    "a good photo of the kind {}",
    "a photo of a thoughtful {}",
    "a close-up photo of the optimistic {}",
    "a rendition of the happy {}",
    "a photo of the creative {}",
    "a rendition of a loving {}",
    "a photo of a nice young {}",
    "a good photo of a talented {}",
    "a photo of the friendly {}",
    "a photo of the small {}",
    "a photo of the energetic {}"
]
